#cloud-config
runcmd:
  - [ sh, -c, "IP=$(curl -s -H 'Metadata-Flavor: Google' http://169.254.169.254/computeMetadata/v1/instance/network-interfaces/0/ip); printf '<h1>Host IP: %s</h1><img src=\"https://storage.yandexcloud.net/${bucket_name}/netology.png\"/>' \"$IP\" > /var/www/html/index.html" ]
  - [ sh, -c, "systemctl restart httpd || systemctl restart apache2" ]
